-- MySQL Script generated by MySQL Workbench
-- Wed May 22 20:59:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabajobd
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trabajobd` ;

-- -----------------------------------------------------
-- Schema trabajobd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabajobd` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `trabajobd` ;

-- -----------------------------------------------------
-- Table `trabajobd`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trabajobd`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trabajobd`.`usuario` (
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nacimiento` date NOT  NULL,
  `seguridad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

DROP TABLE IF EXISTS `trabajobd`.`datoscomplementarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `trabajobd`.`datoscomplementarios` (
  `usuario` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  PRIMARY KEY (`usuario`))
ENGINE = InnoDB;


SHOW WARNINGS;

INSERT INTO `usuario` (`usuario`, `clave`, `email`, `apellidos`, `nombre`, `nacimiento`, `seguridad`) VALUES ('Rafael', '123456', 'rf32@gmail.com', 'Moscardo', 'Rafael', '2000-03-12', 'Husquinia'), 
('Julieta95', '098765', 'julieta95@hotmail.com	', 'Romero Caldereta	', 'Julia', '1995-02-12', 'Romero');

INSERT INTO `datoscomplementarios` (`usuario`, `pais`, `sexo`, `telefono`, `direccion`, `municipio`, `provincia`, `cp`) VALUES ('Rafael', 'España', 'Hombre', '', '', NULL, NULL, ''),
 ('Julieta95', 'España', 'Mujer', NULL, NULL, NULL, NULL, NULL);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
