-- MySQL Script generated by MySQL Workbench
-- Sun May 19 00:59:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema piscina
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `piscina` ;

-- -----------------------------------------------------
-- Schema piscina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `piscina` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `piscina` ;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clientes` (
  `dni` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `clientes`
-- -----------------------------------------------------
START TRANSACTION;
USE `piscina`;
INSERT INTO `clientes` (`dni`, `nombre`, `apellido`, `ciudad`) VALUES (11111, 'Pepe', 'Gil', 'Sevilla');
INSERT INTO `clientes` (`dni`, `nombre`, `apellido`, `ciudad`) VALUES (222222, 'Antonio', 'Luna', 'Huelva');

COMMIT;

